os:
    - linux

sudo: false

env:
    global:
        - LANG=python
        - PYTHON_VERSION=3.5
        - NUMPY_VERSION=1.9
        - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh


matrix:
    include:
        - env: LANG=c
        - os: osx
          env: LANG=c
        - env: LANG=python PYTHON_VERSION=2.6 NUMPY_VERSION=1.9
        - env: LANG=python PYTHON_VERSION=2.7 NUMPY_VERSION=1.6
        - env: LANG=python PYTHON_VERSION=2.7 NUMPY_VERSION=1.7
        - env: LANG=python PYTHON_VERSION=2.7 NUMPY_VERSION=1.8
        - env: LANG=python PYTHON_VERSION=2.7 NUMPY_VERSION=1.9
        - env: LANG=python PYTHON_VERSION=3.3 NUMPY_VERSION=1.9
        - env: LANG=python PYTHON_VERSION=3.4 NUMPY_VERSION=1.9
        - os: osx
          env: LANG=python PYTHON_VERSION=2.7 NUMPY_VERSION=1.9
               MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda-3.7.3-MacOSX-x86_64.sh

before_install:
    - if [[ $LANG == python ]]; then
      wget $MINICONDA_URL -O miniconda.sh;
      chmod +x miniconda.sh;
      ./miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      conda update --yes conda;
      conda create --yes -n test python=$PYTHON_VERSION;
      source activate test;
      conda install --yes numpy=$NUMPY_VERSION pytest cython astropy;
      fi

install:
    - if [[ $LANG == python ]]; then python setup.py install; fi
    - if [[ $LANG == c ]]; then make; fi

script:
    - if [[ $LANG == python ]]; then ./test.py; fi
    - if [[ $LANG == c ]]; then make test; fi
